version: "3.3"

services:
  postgres:
      image: postgres
      shm_size: 1g
      container_name: exjobb.postgres
      expose:
        - "5432"
      ports:
        - "5432:5432"
      environment:
        - POSTGRES_DB=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
  api:
      container_name: exjobb.api
      build: ./flask
      ports:
        - "5000:5000"
      depends_on: 
        - "postgres"
      volumes: ['./flask:/app']
  redis:
      container_name: exjobb.redis
      image: "redis:alpine"